In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp
import sklearn as sk
import tensorflow as tf
import torch as tr

print("Imported successfully")

Imported successfully


In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
print("imported Successfully")


imported Successfully


In [3]:
# Load the Iris Dataset
data = load_iris()
X = data.data #X contains the measurements
y = data.target  #y contains

print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(X.shape)

(150, 4)


In [8]:
#Create a decision Tree Classifier
clf = DecisionTreeClassifier()
print("Done")

Done


In [9]:
#Train the model on the entire dataset
clf.fit(X, y)
print("Trained")

Trained


In [10]:
#Asking the model to predict the species of the first flower in the dataset
prediction = clf.predict([X[0]])                         #The index can be changed when necessary
print(f"Prediction for First sample: {prediction}")
print(f"Actual Species of First sample: {y[0]}")

Prediction for First sample: [0]
Actual Species of First sample: 0


In [11]:
#Asking the model to predict the species of the last flower in the dataset
prediction = clf.predict([X[99]])                         #The index can be changed when necessary
print(f"Prediction for First sample: {prediction}")
print(f"Actual Species of First sample: {y[99]}")

Prediction for First sample: [1]
Actual Species of First sample: 1


In [12]:
from sklearn.model_selection import train_test_split  # split the data into 70% training and 30% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
print("Trained Successfully")

Trained Successfully


In [13]:
clf.fit(X_train, y_train)   #Train on training set
print("Trained")

Trained


In [14]:
y_pred = clf.predict(X_test)   #Test on unseen data
print("Tested")

Tested


In [15]:
from sklearn.metrics import accuracy_score
print("Imported")

Imported


In [16]:
accuracy = accuracy_score(y_test, y_pred)   #Evaluate Accuracy
print("Final Accuracy: ", accuracy)

Final Accuracy:  1.0


In [17]:
from sklearn.metrics import confusion_matrix, classification_report
print("Imported")

Imported


In [18]:
# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [19]:
# Display detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [20]:
# Predict the species of the first flower in the test set
sample_prediction = clf.predict([X_test[0]])
print("\nPrediction for first test sample:", sample_prediction)
print("Actual species of first test sample:", y_test[0])


Prediction for first test sample: [1]
Actual species of first test sample: 1
