<a href="https://colab.research.google.com/github/mojojompe/Huawei-Ai-and-Ml/blob/main/Week%201%20ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp
import sklearn as sk
import tensorflow as tf
import torch as tr

print("Imported successfully")

Imported successfully


In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
print("imported Successfully")


imported Successfully


In [3]:
# Load the Iris Dataset
data = load_iris()
X = data.data #X contains the measurements
y = data.target  #y contains

print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(X.shape)

(150, 4)


In [7]:
#Create a decision Tree Classifier
clf = DecisionTreeClassifier()

In [ ]:
#Train the model on the entire dataset
clf.fit(X, y)


In [ ]:
#Asking the model to predict the species of the first flower in the dataset
prediction = clf.predict([X[0]])                         #The index can be changed when necessary
print(f"Prediction for First sample: {prediction}")
print(f"Actual Species of First sample: {y[0]}")

In [ ]:
from sklearn.model_selection import train_test_split  # split the data into 70% training and 30% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)
print("Trained Successfully")

In [ ]:
clf.fit(X_train, y_train)   #Train on training set
print("Trained")

In [ ]:
y_pred = clf.predict(X_test)   #Test on unseen data
print("Tested")

In [ ]:
accuracy = accuracy_score(y_test, y_pred)   #Evaluate Accuracy
print("Final Accuracy: ", accuracy)